export interface Company{
    ID:string;
    COCODE:string;
    CODESC:string;
    LEGAL_NAME:string; 
    COSCHEME:string;
    COBRANCH:string;
    COREGION:string;
    TAKEON:string;
    TAKEOFF:string;
    ADDR1:string;
    ADDR2 :string;
    ADDR3 :string; 
    POSTCODE :string;
    SADDR1:string; 
    SADDR2 :string;
    SADDR3 :string;
    SPOSTCODE:string; 
    CONTACT:string;
    TELEPHONE:string; 
    FAX :string;
    CATEGORY:string; 
    STATUS :string; 
    CNCL_YN:number; 
    COUNCIL:string;
    MANAGER :string;
    MGCELL :string;
    STEWARD:string;
    STCELL:string;
    GENERAL:string;
   
    // COCODE :string ;
    // CODESC :string ;
    // LEGAL_NAME :string ;
    // COSCHEME : string ;
    // COBRANCH: string ;
    // COREGION: string ;
    // TAKEON :string ;
    // TAKEOFF:string ;
    // ADDR1 :string ;
    // ADDR2 :string ;
    // ADDR3 :string ;
    // ADDR4 :string ;
    // POSTCODE:string ;
    // SADDR1 :string ;
    // SADDR2 :string ;
    // SADDR3 :string ;
    // SADDR4 :string ;
    // SPOSTCODE:string ;
    // CONTACT :string ;
    // TELEPHONE: string ;
    // FAX :string ;
    // CATEGORY :string ;
    // JANMEM :number ;
    // FEBMEM :number ;
    // MARMEM :number ;
    // APRMEM :number ;
    // MAYMEM :number ;
    // JUNMEM :number ;
    // JULMEM :number ;
    // AUGMEM :number ;
    // SEPMEM :number ;
    // OCTMEM :number ;
    // NOVMEM :number ;
    // DECMEM :number ;
    // JAN :number ;
    // FEB :number ;
    // MAR :number ;
    // APR :number ;
    // MAY :number ;
    // JUN :number ;
    // JUL :number ;
    // AUG :number ;
    // SEP :number ;
    // OCT :number ;
    // NOV :number ;
    // DEC :number ;
    // JANMEM2 :number ;
    // FEBMEM2 :number ;
    // MARMEM2 :number ;
    // APRMEM2 :number ;
    // MAYMEM2 :number ;
    // JUNMEM2 :number ;
    // JULMEM2 :number ;
    // AUGMEM2 :number ;
    // SEPMEM2 :number ;
    // OCTMEM2 :number ;
    // NOVMEM2 :number ;
    // DECMEM2 :number ;
    // JAN2 :number ;
    // FEB2 :number ;
    // MAR2 :number ;
    // APR2 :number ;
    // MAY2 :number ;
    // JUN2 :number ;
    // JUL2 :number ;
    // AUG2 :number ;
    // SEP2 :number ;
    // OCT2 :number ;
    // NOV2 :number ;
    // DEC2 :number ;
    // JAN3 :number ;
    // FEB3 :number ;
    // MAR3 :number ;
    // APR3 :number ;
    // MAY3 :number ;
    // JUN3 :number ;
    // JUL3 :number ;
    // AUG3 :number ;
    // SEP3 :number ;
    // OCT3 :number ;
    // NOV3 :number ;
    // DEC3 :number ;
    // AGREE_DT :string ;
    // EXPIRY_DT :string ;
    // ORGANISER string ;
    // STATUS string ;
    // CNCL_YN :boolean ;
    // COUNCIL :string ;
    // FORUM_YN :boolean ;
    // FORUM :string ;
    // CB_YN :boolean ;
    // PB_YN :boolean ;
    // MTH_MEM :number ;
    // MTH_MMYY :string ;
    // WK_MEM :number ;
    // WK_MMYY :string ;
    // WRK_MTH :number ;
    // WRK_MMYY :string ;
    // FLAGGED :boolean) ;
    // GENERAL :string ;
    // RAND_YN :boolean ;
    // MANAGER :string ;
    // MGCELL :string ;
    // STEWARD :string ;
    // STCELL :string ;
 }